name: remember_me_mobile
description: Solution Challenge

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_secure_storage: ^8.0.0
  flutter_screenutil: ^5.6.0
  json_annotation: ^4.7.0
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  skeletons: ^0.0.3
  collection: ^1.16.0
  go_router: ^6.0.1
  retrofit: ^3.3.1
  selectable_autolink_text: ^2.3.0
  intl: ^0.17.0
  introduction_screen: ^3.1.4
  debounce_throttle: ^2.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  image_picker: ^0.8.6
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.11.0"
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSans/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSans/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSans/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSans/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSansKR-Black.otf
          weight: 900
